// Generated by `npm run db:pull` from the database built by db/migrations.
// Don't edit by hand: add a migration, apply it, then re-run db:pull.

import { relations } from "drizzle-orm/relations";
import { user, session, account, profiles, onboarding_responses, subscriptions, subscription_assignments, activity_events, content_batches, content_items, orders, invoices, packages, affiliates, payment_methods, commissions, payouts, notification_log, settings } from "./schema";

export const sessionRelations = relations(session, ({one}) => ({
	user: one(user, {
		fields: [session.userId],
		references: [user.id]
	}),
}));

export const userRelations = relations(user, ({many}) => ({
	sessions: many(session),
	accounts: many(account),
	profiles: many(profiles),
}));

export const accountRelations = relations(account, ({one}) => ({
	user: one(user, {
		fields: [account.userId],
		references: [user.id]
	}),
}));

export const onboarding_responsesRelations = relations(onboarding_responses, ({one}) => ({
	profile: one(profiles, {
		fields: [onboarding_responses.user_id],
		references: [profiles.id]
	}),
}));

export const profilesRelations = relations(profiles, ({one, many}) => ({
	onboarding_responses: many(onboarding_responses),
	user: one(user, {
		fields: [profiles.id],
		references: [user.id]
	}),
	subscription_assignments_profile_id: many(subscription_assignments, {
		relationName: "subscription_assignments_profile_id_profiles_id"
	}),
	subscription_assignments_assigned_by: many(subscription_assignments, {
		relationName: "subscription_assignments_assigned_by_profiles_id"
	}),
	activity_events: many(activity_events),
	content_batches_published_by: many(content_batches, {
		relationName: "content_batches_published_by_profiles_id"
	}),
	content_batches_created_by: many(content_batches, {
		relationName: "content_batches_created_by_profiles_id"
	}),
	content_items: many(content_items),
	invoices: many(invoices),
	orders: many(orders),
	affiliates_user_id: many(affiliates, {
		relationName: "affiliates_user_id_profiles_id"
	}),
	affiliates_approved_by: many(affiliates, {
		relationName: "affiliates_approved_by_profiles_id"
	}),
	payment_methods: many(payment_methods),
	subscriptions: many(subscriptions),
	payouts: many(payouts),
	notification_logs: many(notification_log),
	settings: many(settings),
}));

export const subscription_assignmentsRelations = relations(subscription_assignments, ({one}) => ({
	subscription: one(subscriptions, {
		fields: [subscription_assignments.subscription_id],
		references: [subscriptions.id]
	}),
	profile_profile_id: one(profiles, {
		fields: [subscription_assignments.profile_id],
		references: [profiles.id],
		relationName: "subscription_assignments_profile_id_profiles_id"
	}),
	profile_assigned_by: one(profiles, {
		fields: [subscription_assignments.assigned_by],
		references: [profiles.id],
		relationName: "subscription_assignments_assigned_by_profiles_id"
	}),
}));

export const subscriptionsRelations = relations(subscriptions, ({one, many}) => ({
	subscription_assignments: many(subscription_assignments),
	content_batches: many(content_batches),
	content_items: many(content_items),
	orders: many(orders),
	profile: one(profiles, {
		fields: [subscriptions.user_id],
		references: [profiles.id]
	}),
	package: one(packages, {
		fields: [subscriptions.package_id],
		references: [packages.id]
	}),
	payment_method: one(payment_methods, {
		fields: [subscriptions.payment_method_id],
		references: [payment_methods.id]
	}),
}));

export const activity_eventsRelations = relations(activity_events, ({one}) => ({
	profile: one(profiles, {
		fields: [activity_events.user_id],
		references: [profiles.id]
	}),
}));

export const content_batchesRelations = relations(content_batches, ({one, many}) => ({
	subscription: one(subscriptions, {
		fields: [content_batches.subscription_id],
		references: [subscriptions.id]
	}),
	profile_published_by: one(profiles, {
		fields: [content_batches.published_by],
		references: [profiles.id],
		relationName: "content_batches_published_by_profiles_id"
	}),
	profile_created_by: one(profiles, {
		fields: [content_batches.created_by],
		references: [profiles.id],
		relationName: "content_batches_created_by_profiles_id"
	}),
	content_items: many(content_items),
}));

export const content_itemsRelations = relations(content_items, ({one}) => ({
	subscription: one(subscriptions, {
		fields: [content_items.subscription_id],
		references: [subscriptions.id]
	}),
	content_batch: one(content_batches, {
		fields: [content_items.batch_id],
		references: [content_batches.id]
	}),
	profile: one(profiles, {
		fields: [content_items.uploaded_by],
		references: [profiles.id]
	}),
}));

export const invoicesRelations = relations(invoices, ({one}) => ({
	order: one(orders, {
		fields: [invoices.order_id],
		references: [orders.id]
	}),
	profile: one(profiles, {
		fields: [invoices.user_id],
		references: [profiles.id]
	}),
}));

export const ordersRelations = relations(orders, ({one, many}) => ({
	invoices: many(invoices),
	subscription: one(subscriptions, {
		fields: [orders.subscription_id],
		references: [subscriptions.id]
	}),
	package: one(packages, {
		fields: [orders.package_id],
		references: [packages.id]
	}),
	profile: one(profiles, {
		fields: [orders.user_id],
		references: [profiles.id]
	}),
	affiliate: one(affiliates, {
		fields: [orders.affiliate_id],
		references: [affiliates.id]
	}),
	commissions: many(commissions),
}));

export const packagesRelations = relations(packages, ({many}) => ({
	orders: many(orders),
	subscriptions: many(subscriptions),
}));

export const affiliatesRelations = relations(affiliates, ({one, many}) => ({
	orders: many(orders),
	profile_user_id: one(profiles, {
		fields: [affiliates.user_id],
		references: [profiles.id],
		relationName: "affiliates_user_id_profiles_id"
	}),
	profile_approved_by: one(profiles, {
		fields: [affiliates.approved_by],
		references: [profiles.id],
		relationName: "affiliates_approved_by_profiles_id"
	}),
	commissions: many(commissions),
	payouts: many(payouts),
}));

export const payment_methodsRelations = relations(payment_methods, ({one, many}) => ({
	profile: one(profiles, {
		fields: [payment_methods.user_id],
		references: [profiles.id]
	}),
	subscriptions: many(subscriptions),
}));

export const commissionsRelations = relations(commissions, ({one}) => ({
	affiliate: one(affiliates, {
		fields: [commissions.affiliate_id],
		references: [affiliates.id]
	}),
	order: one(orders, {
		fields: [commissions.order_id],
		references: [orders.id]
	}),
	payout: one(payouts, {
		fields: [commissions.payout_id],
		references: [payouts.id]
	}),
}));

export const payoutsRelations = relations(payouts, ({one, many}) => ({
	commissions: many(commissions),
	affiliate: one(affiliates, {
		fields: [payouts.affiliate_id],
		references: [affiliates.id]
	}),
	profile: one(profiles, {
		fields: [payouts.recorded_by],
		references: [profiles.id]
	}),
}));

export const notification_logRelations = relations(notification_log, ({one}) => ({
	profile: one(profiles, {
		fields: [notification_log.user_id],
		references: [profiles.id]
	}),
}));

export const settingsRelations = relations(settings, ({one}) => ({
	profile: one(profiles, {
		fields: [settings.updated_by],
		references: [profiles.id]
	}),
}));