// Generated by `npm run db:pull` from the database built by db/migrations.
// Don't edit by hand: add a migration, apply it, then re-run db:pull.

import { pgTable, unique, uuid, text, boolean, timestamp, index, foreignKey, jsonb, check, date, bigint, integer, numeric, uniqueIndex, primaryKey, pgView, pgSequence } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"


export const order_number_seq = pgSequence("order_number_seq", {  startWith: "1001", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const invoice_number_seq = pgSequence("invoice_number_seq", {  startWith: "1001", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })

export const user = pgTable("user", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().default('').notNull(),
	email: text().notNull(),
	emailVerified: boolean().default(false).notNull(),
	image: text(),
	phone: text(),
	createdAt: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	accountType: text(),
	companyName: text(),
}, (table) => [
	unique("user_email_key").on(table.email),
]);

export const session = pgTable("session", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	expiresAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	token: text().notNull(),
	createdAt: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	ipAddress: text(),
	userAgent: text(),
	userId: uuid().notNull(),
}, (table) => [
	index("session_user_id_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "session_userId_fkey"
		}).onDelete("cascade"),
	unique("session_token_key").on(table.token),
]);

export const account = pgTable("account", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	accountId: text().notNull(),
	providerId: text().notNull(),
	userId: uuid().notNull(),
	accessToken: text(),
	refreshToken: text(),
	idToken: text(),
	accessTokenExpiresAt: timestamp({ withTimezone: true, mode: 'string' }),
	refreshTokenExpiresAt: timestamp({ withTimezone: true, mode: 'string' }),
	scope: text(),
	password: text(),
	createdAt: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("account_user_id_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [user.id],
			name: "account_userId_fkey"
		}).onDelete("cascade"),
]);

export const verification = pgTable("verification", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	identifier: text().notNull(),
	value: text().notNull(),
	expiresAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	createdAt: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("verification_identifier_idx").using("btree", table.identifier.asc().nullsLast().op("text_ops")),
]);

export const onboarding_responses = pgTable("onboarding_responses", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	user_id: uuid().notNull(),
	business_name: text(),
	industry: text(),
	target_audience: text(),
	brand_voice: text(),
	social_platforms: jsonb().default([]).notNull(),
	brand_colors: text(),
	competitors: text(),
	content_goals: text(),
	assets_url: text(),
	completed: boolean().default(false).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	logo_path: text(),
	social_handles: jsonb().default({}).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [profiles.id],
			name: "onboarding_responses_user_id_fkey"
		}).onDelete("cascade"),
	unique("onboarding_responses_user_id_key").on(table.user_id),
]);

export const profiles = pgTable("profiles", {
	id: uuid().primaryKey().notNull(),
	full_name: text(),
	email: text(),
	company_name: text(),
	role: text().default('client').notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	phone: text(),
	avatar_url: text(),
	is_active: boolean().default(true).notNull(),
	account_type: text().default('individual').notNull(),
	job_title: text(),
	website: text(),
	industry: text(),
	team_size: text(),
	city: text(),
	country: text(),
	bio: text(),
}, (table) => [
	index("profiles_role_idx").using("btree", table.role.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.id],
			foreignColumns: [user.id],
			name: "profiles_id_fkey"
		}).onDelete("cascade"),
	check("profiles_account_type_check", sql`account_type = ANY (ARRAY['individual'::text, 'organization'::text])`),
	check("profiles_role_check", sql`role = ANY (ARRAY['client'::text, 'admin'::text, 'account_manager'::text, 'designer'::text, 'content_creator'::text, 'email_marketer'::text, 'social_media_manager'::text])`),
]);

export const subscription_assignments = pgTable("subscription_assignments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	subscription_id: uuid().notNull(),
	profile_id: uuid().notNull(),
	role: text().notNull(),
	assigned_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("subscription_assignments_profile_id_idx").using("btree", table.profile_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.subscription_id],
			foreignColumns: [subscriptions.id],
			name: "subscription_assignments_subscription_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.profile_id],
			foreignColumns: [profiles.id],
			name: "subscription_assignments_profile_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.assigned_by],
			foreignColumns: [profiles.id],
			name: "subscription_assignments_assigned_by_fkey"
		}).onDelete("set null"),
	unique("subscription_assignments_subscription_id_profile_id_key").on(table.subscription_id, table.profile_id),
	check("subscription_assignments_role_check", sql`role = ANY (ARRAY['account_manager'::text, 'designer'::text, 'content_creator'::text, 'email_marketer'::text, 'social_media_manager'::text])`),
]);

export const activity_events = pgTable("activity_events", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	user_id: uuid(),
	event_type: text().notNull(),
	metadata: jsonb().default({}).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("activity_events_created_at_idx").using("btree", table.created_at.desc().nullsFirst().op("timestamptz_ops")),
	index("activity_events_event_type_idx").using("btree", table.event_type.asc().nullsLast().op("text_ops")),
	index("activity_events_user_id_idx").using("btree", table.user_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [profiles.id],
			name: "activity_events_user_id_fkey"
		}).onDelete("set null"),
]);

export const content_batches = pgTable("content_batches", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	subscription_id: uuid().notNull(),
	title: text().notNull(),
	period_start: date(),
	status: text().default('draft').notNull(),
	client_message: text(),
	internal_notes: text(),
	published_at: timestamp({ withTimezone: true, mode: 'string' }),
	published_by: uuid(),
	created_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("content_batches_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("content_batches_subscription_id_idx").using("btree", table.subscription_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.subscription_id],
			foreignColumns: [subscriptions.id],
			name: "content_batches_subscription_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.published_by],
			foreignColumns: [profiles.id],
			name: "content_batches_published_by_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.created_by],
			foreignColumns: [profiles.id],
			name: "content_batches_created_by_fkey"
		}).onDelete("set null"),
	check("content_batches_status_check", sql`status = ANY (ARRAY['draft'::text, 'published'::text])`),
]);

export const content_items = pgTable("content_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	subscription_id: uuid().notNull(),
	title: text().notNull(),
	description: text(),
	content_type: text(),
	platform: text(),
	status: text().default('requested').notNull(),
	asset_url: text(),
	caption: text(),
	scheduled_for: timestamp({ withTimezone: true, mode: 'string' }),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	batch_id: uuid(),
	storage_path: text(),
	file_name: text(),
	mime_type: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	file_size_bytes: bigint({ mode: "number" }),
	sort_order: integer().default(0).notNull(),
	uploaded_by: uuid(),
}, (table) => [
	index("content_items_batch_id_idx").using("btree", table.batch_id.asc().nullsLast().op("uuid_ops")),
	index("content_items_platform_idx").using("btree", table.platform.asc().nullsLast().op("text_ops")),
	index("content_items_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("content_items_subscription_id_idx").using("btree", table.subscription_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.subscription_id],
			foreignColumns: [subscriptions.id],
			name: "content_items_subscription_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.batch_id],
			foreignColumns: [content_batches.id],
			name: "content_items_batch_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.uploaded_by],
			foreignColumns: [profiles.id],
			name: "content_items_uploaded_by_fkey"
		}).onDelete("set null"),
	check("content_items_status_check", sql`status = ANY (ARRAY['requested'::text, 'draft'::text, 'review'::text, 'approved'::text, 'delivered'::text])`),
]);

export const invoices = pgTable("invoices", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	invoice_number: text().default(sql`(\'INV-\'::text || lpad((nextval(\'invoice_number_seq\'::regclass))::text, 6, \'0\'::text))`).notNull(),
	order_id: uuid().notNull(),
	user_id: uuid().notNull(),
	status: text().default('paid').notNull(),
	currency: text().default('NGN').notNull(),
	subtotal: numeric({ precision: 12, scale: 2, mode: "number" }).notNull(),
	discount_amount: numeric({ precision: 12, scale: 2, mode: "number" }).default(0).notNull(),
	total: numeric({ precision: 12, scale: 2, mode: "number" }).notNull(),
	line_items: jsonb().default([]).notNull(),
	billed_to_name: text(),
	billed_to_email: text(),
	billed_to_company: text(),
	issued_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("invoices_issued_at_idx").using("btree", table.issued_at.desc().nullsFirst().op("timestamptz_ops")),
	index("invoices_user_id_idx").using("btree", table.user_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.order_id],
			foreignColumns: [orders.id],
			name: "invoices_order_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [profiles.id],
			name: "invoices_user_id_fkey"
		}).onDelete("restrict"),
	unique("invoices_invoice_number_key").on(table.invoice_number),
	unique("invoices_order_id_key").on(table.order_id),
	check("invoices_status_check", sql`status = ANY (ARRAY['paid'::text, 'void'::text])`),
]);

export const orders = pgTable("orders", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	order_number: text().default(sql`(\'RAE-\'::text || lpad((nextval(\'order_number_seq\'::regclass))::text, 6, \'0\'::text))`).notNull(),
	user_id: uuid().notNull(),
	subscription_id: uuid().notNull(),
	package_id: uuid().notNull(),
	kind: text().default('new').notNull(),
	status: text().default('pending').notNull(),
	currency: text().default('NGN').notNull(),
	subtotal: numeric({ precision: 12, scale: 2, mode: "number" }).notNull(),
	discount_amount: numeric({ precision: 12, scale: 2, mode: "number" }).default(0).notNull(),
	amount: numeric({ precision: 12, scale: 2, mode: "number" }).notNull(),
	payment_reference: text().notNull(),
	paystack_transaction_id: text(),
	payment_channel: text(),
	paid_at: timestamp({ withTimezone: true, mode: 'string' }),
	failure_reason: text(),
	metadata: jsonb().default({}).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	affiliate_id: uuid(),
	referral_code: text(),
}, (table) => [
	index("orders_affiliate_id_idx").using("btree", table.affiliate_id.asc().nullsLast().op("uuid_ops")),
	uniqueIndex("orders_one_pending_renewal_idx").using("btree", table.subscription_id.asc().nullsLast().op("uuid_ops")).where(sql`((kind = 'renewal'::text) AND (status = 'pending'::text))`),
	index("orders_paid_at_idx").using("btree", table.paid_at.desc().nullsFirst().op("timestamptz_ops")),
	index("orders_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("orders_subscription_id_idx").using("btree", table.subscription_id.asc().nullsLast().op("uuid_ops")),
	index("orders_user_id_idx").using("btree", table.user_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.subscription_id],
			foreignColumns: [subscriptions.id],
			name: "orders_subscription_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.package_id],
			foreignColumns: [packages.id],
			name: "orders_package_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [profiles.id],
			name: "orders_user_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.affiliate_id],
			foreignColumns: [affiliates.id],
			name: "orders_affiliate_id_fkey"
		}).onDelete("set null"),
	unique("orders_order_number_key").on(table.order_number),
	unique("orders_payment_reference_key").on(table.payment_reference),
	check("orders_kind_check", sql`kind = ANY (ARRAY['new'::text, 'renewal'::text])`),
	check("orders_status_check", sql`status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'abandoned'::text, 'refunded'::text])`),
	check("orders_subtotal_check", sql`subtotal >= (0)::numeric`),
	check("orders_discount_amount_check", sql`discount_amount >= (0)::numeric`),
	check("orders_amount_check", sql`amount >= (0)::numeric`),
	check("orders_amount_matches", sql`amount = (subtotal - discount_amount)`),
]);

export const affiliates = pgTable("affiliates", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	user_id: uuid().notNull(),
	code: text().notNull(),
	status: text().default('pending').notNull(),
	discount_percent: numeric({ precision: 5, scale: 2, mode: "number" }).default(10).notNull(),
	commission_percent: numeric({ precision: 5, scale: 2, mode: "number" }).default(10).notNull(),
	bank_name: text(),
	account_number: text(),
	account_name: text(),
	application_note: text(),
	admin_note: text(),
	approved_at: timestamp({ withTimezone: true, mode: 'string' }),
	approved_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("affiliates_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [profiles.id],
			name: "affiliates_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.approved_by],
			foreignColumns: [profiles.id],
			name: "affiliates_approved_by_fkey"
		}).onDelete("set null"),
	unique("affiliates_user_id_key").on(table.user_id),
	unique("affiliates_code_key").on(table.code),
	check("affiliates_code_check", sql`code ~ '^[a-z0-9][a-z0-9-]{2,31}$'::text`),
	check("affiliates_status_check", sql`status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'suspended'::text])`),
	check("affiliates_discount_percent_check", sql`(discount_percent >= (0)::numeric) AND (discount_percent <= (100)::numeric)`),
	check("affiliates_commission_percent_check", sql`(commission_percent >= (0)::numeric) AND (commission_percent <= (100)::numeric)`),
]);

export const payment_methods = pgTable("payment_methods", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	user_id: uuid().notNull(),
	authorization_code: text().notNull(),
	signature: text(),
	email: text().notNull(),
	customer_code: text(),
	channel: text(),
	card_type: text(),
	brand: text(),
	bank: text(),
	last4: text(),
	exp_month: text(),
	exp_year: text(),
	reusable: boolean().default(false).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("payment_methods_user_id_idx").using("btree", table.user_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [profiles.id],
			name: "payment_methods_user_id_fkey"
		}).onDelete("cascade"),
	unique("payment_methods_user_id_signature_key").on(table.user_id, table.signature),
]);

export const paystack_events = pgTable("paystack_events", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "paystack_events_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	event: text().notNull(),
	reference: text(),
	payload: jsonb().notNull(),
	status: text().default('received').notNull(),
	result: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	processed_at: timestamp({ withTimezone: true, mode: 'string' }),
}, (table) => [
	index("paystack_events_created_at_idx").using("btree", table.created_at.desc().nullsFirst().op("timestamptz_ops")),
	index("paystack_events_reference_idx").using("btree", table.reference.asc().nullsLast().op("text_ops")),
	check("paystack_events_status_check", sql`status = ANY (ARRAY['received'::text, 'processed'::text, 'ignored'::text, 'error'::text])`),
]);

export const subscriptions = pgTable("subscriptions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	user_id: uuid().notNull(),
	package_id: uuid().notNull(),
	status: text().default('pending').notNull(),
	payment_reference: text(),
	started_at: timestamp({ withTimezone: true, mode: 'string' }),
	expires_at: timestamp({ withTimezone: true, mode: 'string' }),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	auto_renew: boolean().default(true).notNull(),
	payment_method_id: uuid(),
	renewal_failures: integer().default(0).notNull(),
	last_renewal_attempt_at: timestamp({ withTimezone: true, mode: 'string' }),
	complimentary: boolean().default(false).notNull(),
}, (table) => [
	index("subscriptions_expires_at_idx").using("btree", table.expires_at.asc().nullsLast().op("timestamptz_ops")).where(sql`(status = 'active'::text)`),
	index("subscriptions_package_id_idx").using("btree", table.package_id.asc().nullsLast().op("uuid_ops")),
	index("subscriptions_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("subscriptions_user_id_idx").using("btree", table.user_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [profiles.id],
			name: "subscriptions_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.package_id],
			foreignColumns: [packages.id],
			name: "subscriptions_package_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.payment_method_id],
			foreignColumns: [payment_methods.id],
			name: "subscriptions_payment_method_id_fkey"
		}).onDelete("set null"),
	unique("subscriptions_payment_reference_key").on(table.payment_reference),
	check("subscriptions_status_check", sql`status = ANY (ARRAY['pending'::text, 'active'::text, 'paused'::text, 'cancelled'::text, 'expired'::text])`),
]);

export const commissions = pgTable("commissions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	affiliate_id: uuid().notNull(),
	order_id: uuid().notNull(),
	base_amount: numeric({ precision: 12, scale: 2, mode: "number" }).notNull(),
	rate_percent: numeric({ precision: 5, scale: 2, mode: "number" }).notNull(),
	amount: numeric({ precision: 12, scale: 2, mode: "number" }).notNull(),
	currency: text().default('NGN').notNull(),
	status: text().default('earned').notNull(),
	payout_id: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("commissions_affiliate_id_idx").using("btree", table.affiliate_id.asc().nullsLast().op("uuid_ops")),
	index("commissions_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.affiliate_id],
			foreignColumns: [affiliates.id],
			name: "commissions_affiliate_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.order_id],
			foreignColumns: [orders.id],
			name: "commissions_order_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.payout_id],
			foreignColumns: [payouts.id],
			name: "commissions_payout_id_fkey"
		}).onDelete("set null"),
	unique("commissions_order_id_key").on(table.order_id),
	check("commissions_base_amount_check", sql`base_amount >= (0)::numeric`),
	check("commissions_amount_check", sql`amount >= (0)::numeric`),
	check("commissions_status_check", sql`status = ANY (ARRAY['earned'::text, 'paid'::text, 'void'::text])`),
]);

export const payouts = pgTable("payouts", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	affiliate_id: uuid().notNull(),
	amount: numeric({ precision: 12, scale: 2, mode: "number" }).notNull(),
	currency: text().default('NGN').notNull(),
	method: text().default('bank_transfer').notNull(),
	reference: text(),
	notes: text(),
	paid_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	recorded_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("payouts_affiliate_id_idx").using("btree", table.affiliate_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.affiliate_id],
			foreignColumns: [affiliates.id],
			name: "payouts_affiliate_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.recorded_by],
			foreignColumns: [profiles.id],
			name: "payouts_recorded_by_fkey"
		}).onDelete("set null"),
	check("payouts_amount_check", sql`amount > (0)::numeric`),
]);

export const notification_log = pgTable("notification_log", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "notification_log_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	event: text().notNull(),
	channel: text().notNull(),
	recipient: text().notNull(),
	user_id: uuid(),
	dedupe_key: text(),
	status: text().notNull(),
	provider_id: text(),
	error: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("notification_log_created_at_idx").using("btree", table.created_at.desc().nullsFirst().op("timestamptz_ops")),
	index("notification_log_dedupe_idx").using("btree", table.dedupe_key.asc().nullsLast().op("timestamptz_ops"), table.created_at.desc().nullsFirst().op("text_ops")).where(sql`(dedupe_key IS NOT NULL)`),
	index("notification_log_user_id_idx").using("btree", table.user_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [profiles.id],
			name: "notification_log_user_id_fkey"
		}).onDelete("set null"),
	check("notification_log_channel_check", sql`channel = ANY (ARRAY['email'::text, 'sms'::text])`),
	check("notification_log_status_check", sql`status = ANY (ARRAY['sent'::text, 'failed'::text, 'skipped'::text])`),
]);

export const packages = pgTable("packages", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	slug: text().notNull(),
	description: text(),
	price: numeric({ precision: 12, scale: 2, mode: "number" }).notNull(),
	currency: text().default('NGN').notNull(),
	billing_period: text().default('monthly').notNull(),
	deliverables: jsonb().default([]).notNull(),
	active: boolean().default(true).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	sort_order: integer().default(0).notNull(),
	is_popular: boolean().default(false).notNull(),
}, (table) => [
	index("packages_active_idx").using("btree", table.active.asc().nullsLast().op("bool_ops")),
	unique("packages_slug_key").on(table.slug),
	check("packages_price_check", sql`price >= (0)::numeric`),
	check("packages_billing_period_check", sql`billing_period = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'annual'::text, 'one_time'::text])`),
]);

export const settings = pgTable("settings", {
	key: text().primaryKey().notNull(),
	value: jsonb().default({}).notNull(),
	is_public: boolean().default(false).notNull(),
	description: text(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_by: uuid(),
}, (table) => [
	foreignKey({
			columns: [table.updated_by],
			foreignColumns: [profiles.id],
			name: "settings_updated_by_fkey"
		}).onDelete("set null"),
]);

export const rate_limits = pgTable("rate_limits", {
	key: text().notNull(),
	window_start: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	hits: integer().default(0).notNull(),
}, (table) => [
	primaryKey({ columns: [table.key, table.window_start], name: "rate_limits_pkey"}),
]);
export const affiliate_balances = pgView("affiliate_balances", {	affiliate_id: uuid(),
	user_id: uuid(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	confirmed_sales: bigint({ mode: "number" }),
	earned_total: numeric({ mode: "number" }),
	paid_total: numeric({ mode: "number" }),
	unpaid_total: numeric({ mode: "number" }),
	is_unlocked: boolean(),
}).with({"securityInvoker":true}).as(sql`SELECT a.id AS affiliate_id, a.user_id, count(c.id) FILTER (WHERE c.status <> 'void'::text) AS confirmed_sales, COALESCE(sum(c.amount) FILTER (WHERE c.status <> 'void'::text), 0::numeric) AS earned_total, COALESCE(sum(c.amount) FILTER (WHERE c.status = 'paid'::text), 0::numeric) AS paid_total, COALESCE(sum(c.amount) FILTER (WHERE c.status = 'earned'::text), 0::numeric) AS unpaid_total, count(c.id) FILTER (WHERE c.status <> 'void'::text) >= COALESCE((get_setting('affiliate'::text) ->> 'unlock_threshold'::text)::integer, 50) AS is_unlocked FROM affiliates a LEFT JOIN commissions c ON c.affiliate_id = a.id GROUP BY a.id, a.user_id`);