// Turns drizzle-kit's introspection output (lib/db/generated) into the
// checked-in lib/db/schema.ts and lib/db/relations.ts. Run via
// `npm run db:pull` after adding a migration.
//
// - RLS policies are dropped: they live in db/migrations (the SQL is the
//   source of truth) and drizzle-kit can't introspect their bodies fully.
// - drizzle-kit renders `default ''` as `default(')`; fixed here.
// - numeric columns are read as numbers instead of strings.

import { readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const dir = path.resolve(import.meta.dirname, "..", "lib", "db");
const generated = path.join(dir, "generated");
const header =
  "// Generated by `npm run db:pull` from the database built by db/migrations.\n// Don't edit by hand: add a migration, apply it, then re-run db:pull.\n\n";

let schema = await readFile(path.join(generated, "schema.ts"), "utf8");
schema = schema
  // Policies can span several lines (multi-line SQL in `using`).
  .replace(/\n\s*pgPolicy\([\s\S]*?\}\),(?=\n)/g, "")
  .replace(/\.default\('\)/g, ".default('')")
  .replace(/\bpgPolicy, /, "")
  // Money columns as JS numbers (naira with 2 decimals fit comfortably).
  .replace(/numeric\(\{ precision: (\d+), scale:\s+(\d+) \}\)/g, 'numeric({ precision: $1, scale: $2, mode: "number" })')
  .replace(/numeric\(\)/g, 'numeric({ mode: "number" })')
  .replace(/(mode: "number" \}\))\.default\('([\d.]+)'\)/g, "$1.default($2)");

let relations = await readFile(path.join(generated, "relations.ts"), "utf8");

await writeFile(path.join(dir, "schema.ts"), header + schema);
await writeFile(path.join(dir, "relations.ts"), header + relations);
await rm(generated, { recursive: true, force: true });
console.log("Wrote lib/db/schema.ts and lib/db/relations.ts");
